In [1]:
import numpy as np


# 1: 创建数组

```python
1. np.array() # convert list to array
2. np.full()
3. np.zeros()

```

In [17]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [20]:
np.full((2,3), 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 2: Array $\rightarrow$ 数组 / List $\rightarrow$ 列表

In [6]:
print([1, [1,2,3], True, "apple"], type([1, [1,2,3], True, "apple"]))
print([1, 2,3,4], type([1, 2,3,4]))

[1, [1, 2, 3], True, 'apple'] <class 'list'>
[1, 2, 3, 4] <class 'list'>


In [5]:
print(np.array([1,2,3,4]), type(np.array([1,2,3,4])))

[1 2 3 4] <class 'numpy.ndarray'>


In [7]:
[1,2,3,4]+1

TypeError: can only concatenate list (not "int") to list

In [13]:
[1,2,3,4]-1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [14]:
[1,2,3,4]/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [16]:
[1,2,3,4] * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [12]:
print(np.array([1,2,3,4]))
print(np.array([1,2,3,4]) + 1)
print(np.array([1,2,3,4]) - 1)
print(np.array([1,2,3,4]) * 10)

[1 2 3 4]
[2 3 4 5]
[0 1 2 3]
[10 20 30 40]


# 3: 数组运算

```python
# 返回的是一个标量值，代表整个数组中的最大/小/均值元素
1. np.max()/np.min()/np.mean()

# 比较两个数组中对应位置的元素，返回一个新的数组，新数组中的每个元素是两个输入数组对应位置元素的最大值
2. np.maximum()


# 对二维数组进行矩阵乘法运算。
3. np.dot()/@
```

设 $A=(a_{ij})$ 是一个 $m\times s$ 矩阵，$B=(b_{ij})$ 是一个 $s\times n$ 矩阵，那么它们的乘积 $C = AB$ 是一个 $m\times n$ 矩阵，其中元素 $c_{ij}$ 的计算公式为：

$$
c_{ij}=\sum_{k = 1}^{s}a_{ik}b_{kj}, \quad i = 1,2,\cdots,m; j = 1,2,\cdots,n 
$$

In [24]:
a1 = np.array([1,2,3]) # 一维数组
print(np.max(a1))
print(np.min(a1))
print(np.mean(a1))

3
1
2.0


In [27]:
a2 = np.array([[1,2,3],
             [4,5,6]]) # 二维数组

print(np.max(a2))
print(np.min(a2))
print(np.mean(a2))

6
1
3.5


In [31]:
print(a2)
print()
print(np.max(a2, axis=0)) # 返回每一个column的最大值
print(np.max(a2, axis=1)) # 返回每一个row的最大值

[[1 2 3]
 [4 5 6]]

[4 5 6]
[3 6]


In [43]:
a1 = np.array([[0,200,-3],
             [0,5,6]]) # 二维数组

a2 = np.array([[1,2,3, 5],
             [4,5,6, 9],
              [3,4,5, 8]]) # 二维数组


print(np.maximum(0, a1))
print(a1.shape)
print(a2.shape)

[[  0 200   0]
 [  0   5   6]]
(2, 3)
(3, 4)


In [49]:
print(a1)
print(a2)
print((a1 @ a2).shape)

print(a1 @ a2)


[[  0 200  -3]
 [  0   5   6]]
[[1 2 3 5]
 [4 5 6 9]
 [3 4 5 8]]
(2, 4)
[[ 791  988 1185 1776]
 [  38   49   60   93]]
